### ISSUE TITLE
Find Largest element in an Array using Python

### ISSUE THREAD

**Issue by vedant237** [Namya13Jain/CPP_Guide_Hacktoberfest2023#13]
# Get the size of the array from the user
n = int(input("Enter the number of elements in the array: "))

# Initialize an empty list to store the elements
arr = []

# Take input from the user for each element and add it to the list
for i in range(n):
    element = int(input(f"Enter element {i + 1}: "))
    arr.append(element)

# Initialize a variable to store the largest element
largest = arr[0]

# Iterate through the elements of the array to find the largest
for element in arr:
    if element > largest:
        largest = element

# Print the largest element
print(f"The largest element in the array is: {largest}")

**Comment by Namya13Jain** [comment]
This repo is for C++ language.
