### ISSUE TITLE
Finding the Factorial of a number using Recursion in Python

### ISSUE THREAD

**Issue by vedant237** [Namya13Jain/CPP_Guide_Hacktoberfest2023#15]
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

try:
    number = int(input("Enter a non-negative integer: "))
    if number < 0:
        print("Factorial is not defined for negative numbers.")
    else:
        result = factorial(number)
        print(f"The factorial of {number} is {result}")
except ValueError:
    print("Invalid input. Please enter a valid non-negative integer.")

**Comment by Namya13Jain** [comment]
This repo is for C++ language and not Python language.
