### ISSUE TITLE
Two Sum in Array

### ISSUE THREAD

**Issue by vamsi-spoidey7** [Namya13Jain/CPP_Guide_Hacktoberfest2023#24]
hey  @Namya13Jain  i want to add a question in DSA folder where i will be posting brute, better and optimal solution in C++ , could you please assign this to me under hactoberfest 2023. Having this code along with three sum and four sum will help coders to find pattern in the questions.

**Comment by aniketmdinde** [comment]
Can you assign me this issue for two sum in array.

**Comment by Namya13Jain** [comment]
@vamsi-spoidey7 this issue was already present.
