### ISSUE TITLE
Four Sum in Array

### ISSUE THREAD

**Issue by vamsi-spoidey7** [Namya13Jain/CPP_Guide_Hacktoberfest2023#25]
hey  @Namya13Jain  i want to add a question in DSA folder where i will be posting brute, better and optimal solution in C++ , could you please assign this to me under hactoberfest 2023. Having this code along with two sum and three sum will help coders to find pattern in the questions.

**Comment by Namya13Jain** [comment]
@vamsi-spoidey7 assigned

**Comment by AhtishamJaved** [comment]
can i get the same task?
