### ISSUE TITLE
Reverse List

### ISSUE THREAD

**Issue by Namya13Jain** [Namya13Jain/CPP_Guide_Hacktoberfest2023#4]
Link to problem: https://www.codechef.com/practice/DSAPREP_08/problems/RTLL

**Comment by aniketmdinde** [comment]
how should I contribute to this......

**Comment by Namya13Jain** [comment]
Just start the contribution from 1st October to be considered as a part of Hacktoberfest. Read the Contribution rules from CONTRIBUTING.md file

**Comment by aniketmdinde** [comment]
do I need to create a new file named reverse list after forking to solve this issue

**Comment by trakshan-mishra** [comment]
Please assign this issue to me

**Comment by aniketmdinde** [comment]
Assign this issue to me if possible

**Comment by Namya13Jain** [comment]
@aniketmdinde assigned this issue to you. I'll merge ur PR after 1 Oct.
Thanks!
