### ISSUE TITLE
Finding Arrays are disjoint or not 

### ISSUE THREAD

**Issue by Nikhil-2002** [Namya13Jain/CPP_Guide_Hacktoberfest2023#8]

**Comment by Namya13Jain** [comment]
@Nikhil-2002 kindly add the link to this question.

**Comment by Nikhil-2002** [comment]
if we add link then contributor directly go to the link and solve the issue by copy paste

**Comment by Nikhil-2002** [comment]
https://prepinsta.com/c-program/finding-if-arrays-are-disjoint-or-not/

**Comment by vamsi-spoidey7** [comment]
Please assign this to me

**Comment by Namya13Jain** [comment]
@Nikhil-2002 issue assigned
